# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'V*' # Push events to matching V*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
        exclude:
        - os: windows-latest
          os_name: Windows
        - os: ubuntu-18.04
          os_name: Ubuntu
        - os: macos-latest
          os_name: MacOS

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Packing
      run: |
        pyinstaller -i ./img/calendar.ico -n NUAA_iCal_${{ matrix.os_name }} -F main.py
        
    - name: Generate sha256sum
      id: vars
      env:
        SHA_EXT: sha256sum.txt
      run: |
        filename=$(find ./dist/ -type f)
        sha256sum $filename > $filename.$SHA_EXT
        echo $filename
        echo "::set-output name=filepath::$filename"
        echo "::set-output name=shafilepath::$filename.$SHA_EXT"
        
    - name: Upload to artifact
      uses: actions/upload-artifact@v2
      with:
        name: NUAA_iCal_${{ matrix.os_name }}
        path: ./dist/
